export default {
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      description: 'Page name for the CMS.',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'Unique URL for the page, e.g. home or pricing.',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      description: 'Short description for SEO and notes.',
    },
    {
      name: 'announceBar',
      title: 'Announcement Bar (top strip)',
      type: 'object',
      description: 'Thin strip above the header. Only used on pages that render it (e.g. Home).',
      fields: [
        {
          name: 'enabled',
          title: 'Show bar',
          type: 'boolean',
          initialValue: true,
        },
        {
          name: 'text',
          title: 'Text',
          type: 'string',
          description: 'Lead text before the link, e.g. "NEW: Get Replies Risk-Free And Try Us Out First With A"',
        },
        {
          name: 'linkText',
          title: 'Link Text',
          type: 'string',
          description: 'Underlined link label, e.g. "Free Test Campaign"',
        },
        {
          name: 'linkUrl',
          title: 'Link URL',
          type: 'string',
          description: 'Where the link points, e.g. "/booking"',
        },
        {
          name: 'showArrow',
          title: 'Show arrow (→)',
          type: 'boolean',
          initialValue: true,
        },
      ],
    },
    {
      name: 'sections',
      title: 'Sections',
      type: 'array',
      of: [
        { type: 'heroSection' },
        { type: 'featureSection' },
        { type: 'contentSection' },
        { type: 'testimonialSection' },
        { type: 'statsSection' },
        { type: 'ctaSection' },
        { type: 'logoGridSection' },
        { type: 'partnersSection' },
        { type: 'comparisonSection' },
        { type: 'mechanismSection' },
        { type: 'outreachIntroSection' },
        { type: 'servicesSection' },
        { type: 'caseStudiesSection' },
        { type: 'infoSection' },
        { type: 'reviewsSection' },
        { type: 'faqsSection' },
        { type: 'textImageSection' },
        { type: 'bannerSection' },
        { type: 'tutorialsSection' },
        { type: 'consultationModalSection' },
        { type: 'vslModalSection' },
      ],
    },
  ],
};
