export default {
  name: 'page',
  title: 'Page',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: 'string',
      description: 'Назва сторінки для CMS.',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'Унікальний URL для сторінки, наприклад home або pricing.',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text',
      description: 'Короткий опис для SEO та нотаток.',
    },
    {
      name: 'sections',
      title: 'Sections',
      type: 'array',
      of: [
        { type: 'heroSection' },
        { type: 'featureSection' },
        { type: 'contentSection' },
        { type: 'testimonialSection' },
        { type: 'statsSection' },
        { type: 'ctaSection' },
        { type: 'logoGridSection' },
        { type: 'partnersSection' },
        { type: 'comparisonSection' },
        { type: 'meetingSection' },
        { type: 'mechanismSection' },
        { type: 'servicesSection' },
        { type: 'caseStudiesSection' },
        { type: 'infoSection' },
        { type: 'reviewsSection' },
        { type: 'faqsSection' },
        { type: 'textImageSection' },
        { type: 'bannerSection' },
        { type: 'tutorialsSection' },
      ],
    },
  ],
};
