import page from './page';
import post from './post';
import {
  heroSection,
  featureSection,
  contentSection,
  testimonialSection,
  statsSection,
  ctaSection,
  logoGridSection,
  partnersSection,
  comparisonSection,
  meetingSection,
  mechanismSection,
  servicesSection,
  caseStudiesSection,
  infoSection,
  reviewsSection,
  faqsSection,
  textImageSection,
  bannerSection,
  tutorialsSection,
} from './sections';

export const schemaTypes = [
  page,
  post,
  heroSection,
  featureSection,
  contentSection,
  testimonialSection,
  statsSection,
  ctaSection,
  logoGridSection,
  partnersSection,
  comparisonSection,
  meetingSection,
  mechanismSection,
  servicesSection,
  caseStudiesSection,
  infoSection,
  reviewsSection,
  faqsSection,
  textImageSection,
  bannerSection,
  tutorialsSection,
];
